apiVersion: v1
kind: Service
metadata:
  name: js-login-app
  namespace: login-app
spec:
  selector:
    app: js-login-app
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
  type: ClusterIP
